export const admins = [
    {
        "id": 1,
        "profile": {
            "first_name": "Leanne",
            "last_name": "Graham",
            "cipn": "XX-XXXX",
            "email": "leanne@gmail.com",
            "mobile": "11-111-11",
            "birthday": "11-11-2011",
            "gender": "female",
            "pronoun": "Leanne",
        },
        "groups": [
            "Board Members", "Pro Trainers", "Seniors"
        ],
        "channel_preferences": {
            "email": true,
            "facebook": true,
            "homepage": false,
            "instagram": true,
            "instant_message": true,
            "linkedin": false,
            "sms": true,
            "text_document": true,
            "twitter": true,
        },
        "admin_rights": {
            "edit_rights": true,
            "edit_channels": true,
        },
        "channel_publish_rights": {
            "email": true,
            "facebook": true,
            "homepage": false,
            "instagram": true,
            "instant_message": true,
            "linkedin": false,
            "sms": true,
            "text_document": true,
            "twitter": true,
        }
    },
    {
        "id": 2,
        "profile": {
            "first_name": "Ervin",
            "last_name": "Howell",
            "cipn": "XX-XXXX",
            "email": "Ervin@gmail.com",
            "mobile": "22-222-22",
            "birthday": "22-22-2022",
            "gender": "male",
            "pronoun": "Ervin",
        },
        "groups": [],
        "channel_preferences": {
            "email": false,
            "facebook": true,
            "homepage": false,
            "instagram": true,
            "instant_message": false,
            "linkedin": false,
            "sms": false,
            "text_document": false,
            "twitter": true,
        },
        "admin_rights": {
            "edit_rights": true,
            "edit_channels": false,
        },
        "channel_publish_rights": {
            "email": false,
            "facebook": true,
            "homepage": false,
            "instagram": true,
            "instant_message": false,
            "linkedin": false,
            "sms": false,
            "text_document": false,
            "twitter": true,
        }
    },
    {
        "id": 3,
        "profile": {
            "first_name": "Clementine",
            "last_name": "Bauch",
            "cipn": "XX-XXXX",
            "email": "Clementine@gmail.com",
            "mobile": "33-333-33",
            "birthday": "33-33-2033",
            "gender": "female",
            "pronoun": "Clementine",
        },
        "groups": ["1", "2"],
        "channel_preferences": {
            "email": true,
            "facebook": false,
            "homepage": false,
            "instagram": false,
            "instant_message": true,
            "linkedin": true,
            "sms": false,
            "text_document": true,
            "twitter": true,
        },
        "admin_rights": {
            "edit_rights": false,
            "edit_channels": false,
        },
        "channel_publish_rights": {
            "email": true,
            "facebook": false,
            "homepage": false,
            "instagram": false,
            "instant_message": true,
            "linkedin": true,
            "sms": false,
            "text_document": true,
            "twitter": true,
        }
    },
];